server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/mascotas_db
spring.datasource.username=postgres
spring.datasource.password=joselitodiaz11?
spring.jpa.hibernate.ddl-auto=update

jwt.secret=sanosysalvos1234

spring.kafka.bootstrap-servers=localhost:9092